name: cable
description: A helper to get Ferry to the other side of your project.

version: 0.0.1
repository: https://github.com/rmortes/flutter_cable
homepage: rmort.es

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ferry: ^0.10.4
  ferry_flutter: ^0.5.4
  flutter:
    sdk: flutter
  gql_http_link: ^0.4.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: