name: cable
description: A helper to get Ferry to the other side of your project.

version: 0.0.1
author: Raúl Mortes Illescas
repository: https://github.com/rmortes/flutter_cable
homepage: rmort.es

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: